name: My Workflow

on:
  push:
    branches:
    - source

jobs:
  MyJob:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: source
    - name: Build
      run: |
        make all
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        ./deploy.sh "${GITHUB_TOKEN}"
